CREATE TABLE genes (name TEXT, description TEXT, organism TEXT, sequence TEXT, chromosome TEXT, start INT, end INT, strand VARCHAR(1), translation TEXT); 

CREATE TABLE pathways (name TEXT, description TEXT); 

CREATE TABLE genes (name TEXT, function TEXT, EC INT);

In [1]:
import sqlite3
conn = sqlite3.connect('my.db')
c = conn.cursor()

c.execute("""CREATE TABLE genes (name TEXT, description TEXT, organism TEXT, sequence TEXT); """)

c.execute("""CREATE TABLE pathways (name TEXT, description TEXT);""")

c.execute("""CREATE TABLE enzymes (name TEXT, function TEXT, EC TEXT);""")

conn.commit()

In [2]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('PGM1', 'phosphoglucomutase', 'Homo sapien', 'atggtgaagatcgtgacagttaagacccaggcgtaccaggaccagaagccgggcacgagc
gggctgcggaagcgggtgaaggtgttccagagcagcgccaactacgcggagaacttcatc
cagagtatcatctccaccgtggagccggcgcagcggcaggaggccacgctggtggtgggc
ggggacggccggttctacatgaaggaggccatccagctcatcgctcgcatcgctgccgcc
aacgggatcggtcgcttggttatcggacagaatggaatcctctccacccctgctgtatcc
tgcatcattagaaaaatcaaagccattggtgggatcattctgacagccagtcacaaccca
gggggccccaatggagattttggaatcaaattcaatatttctaatggaggtcctgctcca
gaagcaataactgataaaattttccaaatcagcaagacaattgaagaatatgcagtttgc
cctgacctgaaagtagaccttggtgttctgggaaagcagcagtttgacttggaaaataag
ttcaaacccttcacagtggaaattgtggattcggtagaagcttatgctacaatgctgaga
agcatctttgatttcagtgcactgaaagaactactttctgggccaaaccgactgaagatc
cgtattgatgctatgcatggagttgtgggaccgtatgtaaagaagatcctctgtgaagaa
ctcggtgcccctgcgaactcggcagttaactgcgttcctctggaggactttggaggccac
caccctgaccccaacctcacctatgcagctgacctggtggagaccatgaagtcaggagag
catgattttggggctgcctttgatggagatggggatcgaaacatgattctgggcaagcat
gggttctttgtgaacccttcagactctgtggctgtcattgctgccaacatcttcagcatt
ccgtatttccagcagactggggtccgcggctttgcacggagcatgcccacgagtggtgct
ctggaccgggtggctagtgctacaaagattgctttgtatgagaccccaactggctggaag
ttttttgggaatttgatggacgcgagcaaactgtccctttgtggggaggagagcttcggg
accggttctgaccacatccgtgagaaagatggactgtgggctgtccttgcctggctctcc
atcctagccacccgcaagcagagtgtggaggacattctcaaagatcattggcaaaagtat
ggccggaatttcttcaccaggtatgattacgaggaggtggaagctgagggcgcaaacaaa
atgatgaaggacttggaggccctgatgtttgatcgctcctttgtggggaagcagttctca
gcaaatgacaaagtttacactgtggagaaggccgataactttgaatacagcgacccagtg
gatggaagcatttcaagaaatcagggcttgcgcctcattttcacagatggttctcgaatc
gtcttccgactgagcggcactgggagtgccggggccaccattcggctgtacatcgatagc
tatgagaaggacgttgccaagattaaccaggacccccaggtcatgttggccccccttatt
tccattgctctgaaagtgtcccagctgcaggagaggacgggacgcactgcacccactgtc
atcacctaa');""") 

c.execute("""INSERT INTO enzymes (name, function, EC)
            VALUES ('Isomerase', 'phosphoglucomutase', '5.4.2.2');""")

c.execute("""INSERT INTO pathways (name, description)
            VALUES ('Glycolysis', 'the process of converting glucose into pyruvate and generating small amounts of ATP (energy) and NADH (reducing power).');""")

conn.commit()

In [3]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('pgm', 'phosphoglucomutase', 'E. Coli', 'atggcaatccacaatcgtgcaggccaacctgcacaacagagtgatttgattaacgtcgcc
caactgacggcgcaatattatgtactgaaaccagaagcagggaatgcggagcacgcggtg
aaattcggtacttccggtcaccgtggcagtgcagcgcgccacagctttaacgagccgcac
attctggcgatcgctcaggcaattgctgaagaacgtgcgaaaaacggcatcactggccct
tgctatgtgggtaaagatactcacgccctgtccgaacctgcattcatttccgttctggaa
gtgctggcagcgaacggcgttgatgtcattgtgcaggaaaacaatggcttcaccccgacg
cctgccgtttccaatgccatcctggttcacaataaaaaaggtggcccgctggcagacggt
atcgtgattacaccgtcccataacccgccggaagatggtggaatcaaatacaatccgcca
aatggtggcccggctgataccaacgtcactaaagtggtggaagacagggccaacgcactg
ctggccgatggcctgaaaggcgtgaagcgtatctccctcgacgaagcgatggcatccggt
catgtgaaagagcaggatctggtgcagccgttcgtggaaggtctggccgatatcgttgat
atggccgcgattcagaaagcgggcctgacgctgggcgttgatccgctgggcggttccggt
atcgaatactggaagcgtattggcgagtattacaacctcaacctgactatcgttaacgat
caggtcgatcaaaccttccgctttatgcaccttgataaagacggcgcgatccgtatggac
tgctcctccgagtgtgcgatggcgggcctgctggcactgcgtgataagttcgatctggcg
tttgctaacgacccggattatgaccgtcacggtatcgtcactccggcaggtttgatgaat
ccgaaccactacctggcggtggcaatcaattacctgttccagcatcgtccgcagtggggc
aaagatgttgccgtcggtaaaacgctggtttcatctgcgatgatcgaccgtgtggtcaac
gacttgggccgtaaactggtagaagtcccggtaggtttcaaatggtttgtcgatggtctg
ttcgacggcagcttcggctttggcggcgaagagagtgcaggggcttccttcctgcgtttc
gacggcacgccgtggtccaccgacaaagacggcatcatcatgtgtctgctggcggcggaa
atcaccgctgtcaccggtaagaacccgcaggaacactacaacgaactggcaaaacgcttt
ggtgcgccgagctacaaccgtttgcaggcagctgcgacttccgcacaaaaagcggcgctg
tctaagctgtctccggaaatggtgagcgccagcaccctggcaggtgacccgatcaccgcg
cgcctgactgctgctccgggcaacggtgcttctattggcggtctgaaagtgatgactgac
aacggctggttcgccgcgcgtccgtcaggcacggaagacgcatataagatctactgcgaa
agcttcctcggtgaagaacatcgcaagcagattgagaaagaagcggttgagattgttagc
gaagttctgaaaaacgcgtaa');""") 

conn.commit()

In [4]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('pgm2B', 'phosphoglucomutase', 'Drosophila', 'atgtctatctcagtgaagcggaaaacggtgatttcaccgcaggaactcctgaagacactc
gagctgtccggcgaagaggacctcgatctgcagatcaagaactgggtgatgtgggaccgc
aacgaggcgacgctccagcaggtgactgaggcagtcagggatcaggattggaaggcgttg
cgggtgagactgtgccataggatcacctatttgacaactggcttgaggggagtgatgcgc
gcaggcttcgactctttgaacgatgtggtgatcatcgaagtggcccagggcatctgcgcc
tacctcgtcgatgcctatccaagcatccagaagaggcaaacacagggcgtggtcgttggc
tacgatggcaggtacaatagcaagcggtttgcccaactcatcgccaccgtgttcctgaac
aacgacttcaaggtgttcctcttcactcggatgatcccgacaccctttatacccttcacc
gtcgtcacgctccagtgcctggcggggatcgtggtcactgcctcccacaacgttaaggag
gacaatggcatcaaggtatattggtcgaatggggctcaggcgatggcaccgcacgatcag
cggattcatgactatatgatgaataacctagaaccaaagccttcgtcctgggaaacttca
ctggtacttgaccatcccttggtggaggatccctatcgtcagatatacccactcttttac
gaggctctcaagacgcttattcccccaatttacctggaaactaatgagtgcagccagttg
aggttcatctatacagctcttcacggtgtgggttatcccttcatgagggaggccttctac
caggcgcgactcaagccggttattcccgtcgtggaacagaaagaggccgatccagagttt
cccaccctcgttaaaccaaatccggaagagggcaaggaagcgctgaagctggccataaag
aaggcggatgcggaacactgcaccttggttctggccaatgatccggatgtggatcgcttg
gctgtggcagagctggatccgcgtggccgctggaagctgttcaatggcaacgaactgggt
gccctgctcggctggtgggcactggagaactacaagactaggacacccaagccagcagtg
accaattgcataatgatagccacactggtcagctcacgcatcctggcggcaatggcgaga
gttgagggcttcatctttgtggagggcatgcccagtttcccctggatggcacatcgcgcc
ttggagctggaaaagtctggaagaacagtactatttgcatttgaggagtgctttggctat
atgttcggaatgagcctgccggataaggatggcattggagctgccatgcagttggccagc
atggcctgttatctgcgcagcactagaaatgtgacgctgatcgagaagctaagggagatc
tacgatacgtatggctaccattcgtcgatctcgtcggtttatatggccgatagtccagag
acaatcactagcgtcttcgatcatttgcgcaactttacggacgaagagggatatccgaag
ttcattctggatgaagaattcgaagtggttcatatccgggatttgaccatcggactggac
acttccttcagcgatggaaaggctcgtatgccggtcactccagatgcccagctaattacg
tttaccttcaccaatggctatgtggttaccctgcgatcggcacccaacgatattaagatc
aaacttaatgcggagatctgtggcttgccggaggaaaagcagtgggaggagctacacgat
aaactgaacaggatgaccaatgccgtggtggaggagtttcttcaaccagaggagaatggt
cttacggatgcctcaacaattcaataa');""") 

conn.commit()

In [5]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('pgi', 'glucose-6-phosphate isomerase', 'E. Coli', 'atgaaaaacatcaatccaacgcagaccgctgcctggcaggcactacagaaacacttcgat
gaaatgaaagacgttacgatcgccgatctttttgctaaagacggcgatcgtttttctaag
ttctccgcaaccttcgacgatcagatgctggtggattactccaaaaaccgcatcactgaa
gagacgctggcgaaattacaggatctggcgaaagagtgcgatctggcgggcgcgattaag
tcgatgttctctggcgagaagatcaaccgcactgaaaaccgcgccgtgctgcacgtagcg
ctgcgtaaccgtagcaataccccgattttggttgatggcaaagacgtaatgccggaagtc
aacgcggtgctggagaagatgaaaaccttctcagaagcgattatttccggtgagtggaaa
ggttataccggcaaagcaatcactgacgtagtgaacatcgggatcggcggttctgacctc
ggcccatacatggtgaccgaagctctgcgtccgtacaaaaaccacctgaacatgcacttt
gtttctaacgtcgatgggactcacatcgcggaagtgctgaaaaaagtaaacccggaaacc
acgctgttcttggtagcatctaaaaccttcaccactcaggaaactatgaccaacgcccat
agcgcgcgtgactggttcctgaaagcggcaggtgatgaaaaacacgttgcaaaacacttt
gcggcgctttccaccaatgccaaagccgttggcgagtttggtattgatactgccaacatg
ttcgagttctgggactgggttggcggccgttactctttgtggtcagcgattggcctgtcg
attgttctctccatcggctttgataacttcgttgaactgctttccggcgcacacgcgatg
gacaagcatttctccaccacgcctgccgagaaaaacctgcctgtactgctggcgctgatt
ggcatctggtacaacaatttctttggtgcggaaactgaagcgattctgccgtatgaccag
tatatgcaccgtttcgcggcgtacttccagcagggcaatatggagtccaacggtaagtat
gttgaccgtaacggtaacgttgtggattaccagactggcccgattatctggggtgaacca
ggcactaacggtcagcacgcgttctaccagctgatccaccagggaaccaaaatggtaccg
tgcgatttcatcgctccggctatcacccataacccgctctctgatcatcaccagaaactg
ctgtctaacttcttcgcccagaccgaagcgctggcgtttggtaaatcccgcgaagtggtt
gagcaggaatatcgtgatcagggtaaagatccggcaacgcttgactacgtggtgccgttc
aaagtattcgaaggtaaccgcccgaccaactccatcctgctgcgtgaaatcactccgttc
agcctgggtgcgttgattgcgctgtatgagcacaaaatctttactcagggcgtgatcctg
aacatcttcaccttcgaccagtggggcgtggaactgggtaaacagctggcgaaccgtatt
ctgccagagctgaaagatgataaagaaatcagcagccacgatagctcgaccaatggtctg
attaaccgctataaagcgtggcgcggttaa');""") 

c.execute("""INSERT INTO enzymes (name, function, EC)
            VALUES ('Isomerase', 'glucose-6-phosphatase isomerase', '5.3.1.9');""")

conn.commit()

In [6]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('GPI', 'glucose-6-phosphate isomerase', 'Homo sapien', 'atggccgctctcacccgggacccccagttccagaagctgcagcaatggtaccgcgagcac
cgctccgagctgaacctgcgccgcctcttcgatgccaacaaggaccgcttcaaccacttc
agcttgaccctcaacaccaaccatgggcatatcctggtggattactccaagaacctggtg
acggaggacgtgatgcggatgctggtggacttggccaagtccaggggcgtggaggccgcc
cgggagcggatgttcaatggtgagaagatcaactacaccgagggtcgagccgtgctgcac
gtggctctgcggaaccggtcaaacacacccatcctggtagacggcaaggatgtgatgcca
gaggtcaacaaggttctggacaagatgaagtctttctgccagcgtgtccggagcggtgac
tggaaggggtacacaggcaagaccatcacggacgtcatcaacattggcattggcggctcc
gacctgggacccctcatggtgactgaagcccttaagccatactcttcaggaggtccccgc
gtctggtatgtctccaacattgatggaactcacattgccaaaaccctggcccagctgaac
cccgagtcctccctgttcatcattgcctccaagacctttactacccaggagaccatcacg
aatgcagagacggcgaaggagtggtttctccaggcggccaaggatccttctgcagtggcg
aagcactttgttgccctgtctactaacacaaccaaagtgaaggagtttggaattgaccct
caaaacatgttcgagttctgggattgggtgggaggacgctactcgctgtggtcggccatc
ggactctccattgccctgcacgtgggttttgacaacttcgagcagctgctctcgggggct
cactggatggaccagcacttccgcacgacgcccctggagaagaacgcccccgtcttgctg
gccctgctgggtatctggtacatcaactgctttgggtgtgagacacacgccatgctgccc
tatgaccagtacctgcaccgctttgctgcgtacttccagcagggcgacatggagtccaat
gggaaatacatcaccaaatctggaacccgtgtggaccaccagacaggccccattgtgtgg
ggggagccagggaccaatggccagcatgctttttaccagctcatccaccaaggcaccaag
atgataccctgtgacttcctcatcccggtccagacccagcaccccatacggaagggtctg
catcacaagatcctcctggccaacttcttggcccagacagaggccctgatgaggggaaaa
tcgacggaggaggcccgaaaggagctccaggctgcgggcaagagtccagaggaccttgag
aggctgctgccacataaggtctttgaaggaaatcgcccaaccaactctattgtgttcacc
aagctcacaccattcatgcttggagccttggtcgccatgtatgagcacaagatcttcgtt
cagggcatcatctgggacatcaacagctttgaccagtggggagtggagctgggaaagcag
ctggctaagaaaatagagcctgagcttgatggcagtgctcaagtgacctctcacgacgct
tctaccaatgggctcatcaacttcatcaagcagcagcgcgaggccagagtccaataa');""") 

conn.commit()

In [7]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('Pgi', 'glucose-6-phosphate isomerase', 'Drosophila', 'atggccggcccacttcctccgctcaaccaggaggcagcgttccagaagctgcaggagtac
tacgactccaagggcaaggacctgaacatcaaggacctgttcgtgaaggattccaagaga
ttctcaaaatacagcctgcgcctgcacacccagaacgatggcgagatactgctggactac
tcgaagaaccgtatcaatgacgaggtctgggatctgctcctcaccctggccaaggtgcgc
cgcgttaacgccgcgcgggacgccatgttctccggccagcacattaacatcacggagaac
cgcgccgtcctccacacggccctgcgcaaccgcggcacggatcccgtcctggtggacgac
aaggacgtgatgcccgatgtgcgcgccgaactggcccacatgaaggagttcaccaacatg
gtcatctccggcgtgtggcgcggctgcaccggcaaacagatcaccgacgtggtcaacatc
ggcatcggtggctccgatctgggcccgctgatggtcaccgaagcgctgaagccctacggc
aagggccttcactcccactttgtgtcgaacatcgatggcactcatctggccgaggtcctc
aagaaggtcaactacgagaccaccctcttcattgtcgcctcaaaaactttcaccacccag
gagaccattacgaacgccacctccgccaagacctggctcctggagcattccaaggagcct
gagtccgtggccaagcattttgtggccctgtcgaccaacaaggaaaaggtcaccgaattc
ggcattgacagcaccaacatgttcggtttttgggattgggtgggcggtcgctactccctg
tggtcggccattggactgtcaatctgtctgtccattggctttgagaactttgagcaactg
ctggatggagctcacttcatggacaaccatttcaagacgacaccattcgagaagaatgct
cctgttatcctggcgttgctaggcgtttggtactccaacttcttcaaggcggaaacacat
gccctccttccctacgatcagtacttgcaccggttcgccgcctacttccagcagggcgat
atggagagcaacggcaagttcgtcagcaagtcgggcaaacccgtcaagtacagcactggt
ccgatcgtgtggggcgagcctggcaccaatggccagcacgccttctaccagctcatccac
cagggcacccgcctgatcccctgcgatttcatcgctcccgcccagacacacaatcccatt
gccggcggcaagcaccacaagattctgctatcgaatttccttgcccagacggaggcttta
atggccggaaagacggtcgacgaggccaggaccgagctgtccaaggctggcctgtgcggc
aacgagctggataacttgttgccccacaaggtgttcgtcggcaaccggcccacaaactcg
attgtggtgaagaaggtttcacctttcaccctaggcgcgttgattgcgctgtacgagcac
aagatcttcgttcagggcatcatttgggacatcaactcgttcgaccaatggggtgtggag
ctgggcaagcagctggccaaggccatcgagccggagctggatcactgcaacgaggtctcc
acgcacgacagttccacgaacggtctaattaacttcatcaaagccaattggaagtaa');""") 

conn.commit()

In [8]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('pfkB', '6-phosphofructokinase 2', 'E. Coli', 'atgattaagaaaatcggtgtgttgacaagcggcggtgatgcgccaggcatgaacgccgca
attcgcggggttgttcgttctgcgctgacagaaggtctggaagtaatgggtatttatgac
ggctatctgggtctgtatgaagaccgtatggtacagctagaccgttacagcgtgtctgac
atgatcaaccgtggcggtacgttcctcggttctgcgcgtttcccggaattccgcgacgag
aacatccgcgccgtggctatcgaaaacctgaaaaaacgtggtatcgacgcgctggtggtt
atcggcggtgacggttcctacatgggtgcaatgcgtctgaccgaaatgggcttcccgtgc
atcggtctgccgggcactatcgacaacgacatcaaaggcactgactacactatcggtttc
ttcactgcgctgagcaccgttgtagaagcgatcgaccgtctgcgtgacacctcttcttct
caccagcgtatttccgtggtggaagtgatgggccgttattgtggagatctgacgttggct
gcggccattgccggtggctgtgaattcgttgtggttccggaagttgaattcagccgtgaa
gacctggtaaacgaaatcaaagcgggtatcgcgaaaggtaaaaaacacgcgatcgtggcg
attaccgaacatatgtgtgatgttgacgaactggcgcatttcatcgagaaagaaaccggt
cgtgaaacccgcgcaactgtgctgggccacatccagcgcggtggttctccggtgccttac
gaccgtattctggcttcccgtatgggcgcttacgctatcgatctgctgctggcaggttac
ggcggtcgttgtgtaggtatccagaacgaacagctggttcaccacgacatcatcgacgct
atcgaaaacatgaagcgtccgttcaaaggtgactggctggactgcgcgaaaaaactgtat
taa');""") 

c.execute("""INSERT INTO enzymes (name, function, EC)
            VALUES ('Transferase', '6-phosphofructokinase', '2.7.1.11');""")

conn.commit()

In [9]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('PFKL', '6-phosphofructokinase 1', 'Homo sapien', 'atggccgcggtggacctggagaagctgcgggcgtcgggcgcgggcaaggccatcggcgtc
ctgaccagcggcggcgacgcgcaaggcatgaacgctgctgtccgggctgtgacgcgcatg
ggcatttatgtgggtgccaaagtcttcctcatctacgagggctatgagggcctcgtggag
ggaggtgagaacatcaagcaggccaactggctgagcgtctccaacatcatccagctgggc
ggcactatcattggcagcgctcgctgcaaggcctttaccaccagggaggggcgccgggca
gcggcctacaacctggtccagcacggcatcaccaacctgtgcgtcatcggcggggatggc
agcctcacaggtgccaacatcttccgcagcgagtggggcagcctgctggaggagctggtg
gcggaaggtaagatctcagagactacagcccggacctactcgcacctgaacatcgcgggc
ctagtgggctccatcgataacgacttctgcggcaccgacatgaccatcggcacggactcg
gccctccaccgcatcatggaggtcatcgatgccatcaccaccactgcccagagccaccag
aggaccttcgtgctggaagtgatgggccggcactgcgggtacctggcgctggtatctgca
ctggcctcaggggccgactggctgttcatccccgaggctccacccgaggacggctgggag
aacttcatgtgtgagaggctgggtgagactcggagccgtgggtcccgactgaacatcatc
atcatcgctgagggtgccattgaccgcaacgggaagcccatctcgtccagctacgtgaag
gacctggtggttcagaggctgggcttcgacacccgtgtaactgtgctgggccacgtgcag
cggggagggacgccctctgccttcgaccggatcctgagcagcaagatgggcatggaggcg
gtgatggcgctgctggaagccacgcctgacacgccggcctgcgtggtcaccctctcgggg
aaccagtcagtgcggctgcccctcatggagtgcgtgcagatgaccaaggaagtgcagaaa
gccatggatgacaagaggtttgacgaggccacccagctccgtggtgggagcttcgagaac
aactggaacatttacaagctcctcgcccaccagaagccccccaaggagaagtctaacttc
tccctggccatcctgaatgtgggggccccggcggctggcatgaatgcggccgtgcgctcg
gcggtgcggaccggcatctcccatggacacacagtatacgtggtgcacgatggcttcgaa
ggcctagccaagggtcaggtgcaagaagtaggctggcacgacgtggccggctggttgggg
cgtggtggctccatgctggggaccaagaggaccctgcccaagggccagctggagtccatt
gtggagaacatccgcatctatggtattcacgccctgctggtggtcggtgggtttgaggcc
tatgaaggggtgctgcagctggtggaggctcgcgggcgctacgaggagctctgcatcgtc
atgtgtgtcatcccagccaccatcagcaacaacgtccctggcaccgacttcagcctgggc
tccgacactgctgtaaatgccgccatggagagctgtgaccgcatcaaacagtctgcctcg
gggaccaagcgccgtgtgttcatcgtggagaccatggggggttactgtggctacctggcc
accgtgactggcattgctgtgggggccgacgccgcctacgtcttcgaggaccctttcaac
atccacgacttaaaggtcaacgtggagcacatgacggagaagatgaagacagacattcag
aggggcctggtgctgcggaacgagaagtgccatgactactacaccacggagttcctgtac
aacctgtactcatcagagggcaagggcgtcttcgactgcaggaccaatgtcctgggccac
ctgcagcagggtggcgctccaaccccctttgaccggaactatgggaccaagctgggggtg
aaggccatgctgtggttgtcggagaagctgcgcgaggtttaccgcaagggacgggtgttc
gccaatgccccagactcggcctgcgtgatcggcctgaagaagaaggcggtggccttcagc
cccgtcactgagctcaagaaagacactgatttcgagcaccgcatgccacgggagcagtgg
tggctgagcctgcggctcatgctgaagatgctggcacaataccgcatcagtatggccgcc
tacgtgtcaggggagctggagcacgtgacccgccgcaccctgagcatggacaagggcttc
tga');""") 

conn.commit()

In [10]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('Pfk', '6-phosphofructokinase 1', 'Drosophila', 'atgaattccgagattaatcaacgattcctggcccgcggctcgcagaaggacaaaggactg
gcggtcttcaccagcggcggggattcccagggcatgaatgccgccgtgcgagcctgtgtc
cgtatggccatctatttgggctgcaaggtctacttcattcgtgaaggctaccagggcatg
gtggatggtggcgactgcatccaggaagccaactgggcctcagtctcatccattatccat
cgtggtggcaccatcattggctccgcccgttgccaggacttccgtgagcgtcagggtcgc
ttgaaagccgctaacaacctgattcagcgaggaatcaccaatctggtggtcattggaggc
gatggctccctcacgggcgccaatctgttccgtcaggagtggtccagcctgttggacgag
ctggtcaagaacaagaccattaccaccgagcagcaggagaagttcaatgtcctgcacatc
gttggattggttggctccatcgacaacgatttctgtggcactgacatgaccatcggcacg
gacacggcactacatcgcatcatcgaggcaatcgatgccatctccagtacagcctactcc
catcagcgcaccttcatcatggaggtcatgggtcgtcattgcggctatttagctcttgtg
ggtggactggcgtgcgaggcggatttcatattcattcccgaaatgccgcccaaggtcgat
tggccagacaggctctgctctcagctggcccaggagcgatctgctggccagcgtctgaac
atcgtgattgtggccgagggagccatggatcgcgagggtcatcccatcacagccgaggat
gtaaagaaggtgatcgacgagcgtctgaagcacgatgcccgcatcactgtcttgggtcac
gtgcagcgcggtggcaatcccagtgccttcgatcgtattttggcttgccgcatgggagct
gaggccactttggccctgatggaggccaccaaggactcggtgccagtggtcatctctctg
gacggcaaccaggcggttcgcgtgccgctgatggagtgcgtagagcgcacccaggctgtg
gccaaggccatggcggagaaacgctgggcggatgccgtcaagctgcgcggacgctccttc
gagcggaatctggagacctacaagatgctgacgcgcttgaagccgcccaaggagaacttc
gacgccgatggcaagggaatcgaaggataccgcctagctgtgatgcatattggtgctccg
gcttgcggtatgaatgccgctgtgcgcagcttcgtgcgcaatgccatctaccgcggtgat
gtggtttatggaatcaacgacggtgtcgagggtctgattgccggaaatgtccgcgagctg
ggctggtcggatgtctcaggatgggttggtcagggtggcgcctacttgggtaccaaacgc
acactgcctgagggcaagttcaaggagatcgccgctcgtctcaaggagtttaagatccag
ggtctcctgatcattggtggctttgagagttaccatgccgccggacagatcgccgatcag
cgggacaactacccacagttctgcatccccattgtggttattccatcgacgatttcgaac
aatgtgcccggcacagaattttctctgggatgcgacaccggtttaaatgagattacggag
atttgcgaccgtatccgtcagtcggcacagggaaccaagcgccgagtgttcgtcattgag
acgatgggtggctactgtggctatttggccaccttggccggcttggccggcggagctgat
gccgcctacatctacgaggagaagttctccatcaaagacctgcagcaggatgtctaccac
atggcctccaagatggccgagggcgtctcccgcggtctaatcctgcgaaacgagaaggct
agcgagaactacagcacggacttcatttaccgcctgtactcggaggagggcaagggcctc
ttcacctgccgtatgaacatcctgggtcacatgcagcagggcggctcacccactcccttc
gaccgcaacatgggcaccaaaatggccgccaagtgtgtcgactggctggccgcccagatc
aaggcgaacatcgacgccaacggcgtagtcaactgcaagtccccggacaccgccacgctg
ctgggaatcgtgtcgcggcagtaccgcttctcaccgctggtcgacctcattgcagagacg
aacttcgatcaacgcatcccgaagaagcagtggtggctgcgcctgcgtcccctgctgcgc
atcctggccaagcacgattccgcctacgaggaggagggtatgtacatcaccgtcgaggag
gagtgtgacactgacgccgtcgcctaa');""") 

conn.commit()

In [11]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('fdaB', 'fructose-bisphosphate aldolase, class I', 'E. Coli', 'atgtctaagatttttgatttcgtaaaacctggcgtaatcactggtgatgacgtacagaaa
gttttccaggtagcaaaagaaaacaacttcgcactgccagcagtaaactgcgtcggtact
gactccatcaacgccgtactggaaaccgctgctaaagttaaagcgccggttatcgttcag
ttctccaacggtggtgcttcctttatcgctggtaaaggcgtgaaatctgacgttccgcag
ggtgctgctatcctgggcgcgatctctggtgcgcatcacgttcaccagatggctgaacat
tatggtgttccggttatcctgcacactgaccactgcgcgaagaaactgctgccgtggatc
gacggtctgttggacgcgggtgaaaaacacttcgcagctaccggtaagccgctgttctct
tctcacatgatcgacctgtctgaagaatctctgcaagagaacatcgaaatctgctctaaa
tacctggagcgcatgtccaaaatcggcatgactctggaaatcgaactgggttgcaccggt
ggtgaagaagacggcgtggacaacagccacatggacgcttctgcactgtacacccagccg
gaagacgttgattacgcatacaccgaactgagcaaaatcagcccgcgtttcaccatcgca
gcgtccttcggtaacgtacacggtgtttacaagccgggtaacgtggttctgactccgacc
atcctgcgtgattctcaggaatatgtttccaagaaacacaacctgccgcacaacagcctg
aacttcgtattccacggtggttccggttctactgctcaggaaatcaaagactccgtaagc
tacggcgtagtaaaaatgaacatcgataccgatacccaatgggcaacctgggaaggcgtt
ctgaactactacaaagcgaacgaagcttatctgcagggtcagctgggtaacccgaaaggc
gaagatcagccgaacaagaaatactacgatccgcgcgtatggctgcgtgccggtcagact
tcgatgatcgctcgtctggagaaagcattccaggaactgaacgcgatcgacgttctgtaa');""") 

c.execute("""INSERT INTO enzymes (name, function, EC)
            VALUES ('Lyase', 'fructose-bisphosphate aldolase', '4.1.2.13');""")

conn.commit()

In [12]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('ALDOA', 'fructose-bisphosphate aldolase, class I', 'Homo sapien', 'atgccctaccaatatccagcactgaccccggagcagaagaaggagctgtctgacatcgct
caccgcatcgtggcacctggcaagggcatcctggctgcagatgagtccactgggagcatt
gccaagcggctgcagtccattggcaccgagaacaccgaggagaaccggcgcttctaccgc
cagctgctgctgacagctgacgaccgcgtgaacccctgcattgggggtgtcatcctcttc
catgagacactctaccagaaggcggatgatgggcgtcccttcccccaagttatcaaatcc
aagggcggtgttgtgggcatcaaggtagacaagggcgtggtccccctggcagggacaaat
ggcgagactaccacccaagggttggatgggctgtctgagcgctgtgcccagtacaagaag
gacggagctgacttcgccaagtggcgttgtgtgctgaagattggggaacacaccccctca
gccctcgccatcatggaaaatgccaatgttctggcccgttatgccagtatctgccagcag
aatggcattgtgcccatcgtggagcctgagatcctccctgatggggaccatgacttgaag
cgctgccagtatgtgaccgagaaggtgctggctgctgtctacaaggctctgagtgaccac
cacatctacctggaaggcaccttgctgaagcccaacatggtcaccccaggccatgcttgc
actcagaagttttctcatgaggagattgccatggcgaccgtcacagcgctgcgccgcaca
gtgccccccgctgtcactgggatcaccttcctgtctggaggccagagtgaggaggaggcg
tccatcaacctcaatgccattaacaagtgccccctgctgaagccctgggccctgaccttc
tcctacggccgagccctgcaggcctctgccctgaaggcctggggcgggaagaaggagaac
ctgaaggctgcgcaggaggagtatgtcaagcgagccctggccaacagccttgcctgtcaa
ggaaagtacactccgagcggtcaggctggggctgctgccagcgagtccctcttcgtctct
aaccacgcctattaa');""") 

conn.commit()

In [13]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('Ald2', 'fructose-bisphosphate aldolase, class I', 'Drosophila', 'atgactacgcatttctactacccgaacaaggagctgcaggaagaactcatctgcatatcg
aaggcgttggtggctcctggtaagggaatcctggcggccgacgagtccagtgcagtgatg
ggcaagcgatttcagttgatcggtgtggagaacacggaggagaatcgccggctataccgc
caaatgctattcacgaccgatccgaagatagcggagaatatatccggcgtgatattctac
catgaaacactgcatcagcgtacggatgacggactgccattcgtagaggccctcagaaag
aagggcatcctgacgggaataaaggtagacaagcacttttcaccactcttcggctccgag
gatgagttcaccacccagggtctggatgatctagccaatcgatgtgcacagtacaagaag
gagggctgcagctttgccaagtggaggtgcatcctgaagatcactaagaatactccttcg
ccgcaggccattttggaaaacgctaatgtcatggcccggtatgcagccatctgtcaatcg
cagcgactagtacccatcattagtcccgaggtcctggccaccggagatcatgacttggat
cggtgtcagaaggtcaacgaaattctcctggctggagtatacaaggctcttagtgatcac
cacgtttttctcgagggaactcttttgcaacccagcatggtgatgcctggattgcagagc
aacaaaaatcatccgccagcggatattggagtggctacagttctcgccattaggcgaagt
gttcctccggccgtaatgggagtacttttttgtggtggcgctcaatcagaagaggaggcc
acggtccatttgaatgcaattaacaatgttccgctttgtaagccttgggccatgaccttt
gcctttgatcgggctcttcaaacatcgattttgcgaacttggggtggcaagaaggagcag
attagccatgctcaaaatgaacttatcaagcggtgcagggccaatggtcttgcaagcatt
ggaaaatatgtaattggctctgtggaaagttcagcggccactgaaagactcattcaagaa
gccgtcgaattctaa');""") 

conn.commit()

In [14]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('rpiA', 'ribose 5-phosphate isomerase A', 'E. Coli', 'atgacgcaggatgaattgaaaaaagcagtaggatgggcggcacttcagtatgttcagccc
ggcaccattgttggtgtaggtacaggttccaccgccgcacactttattgacgcgctcggt
acaatgaaaggccagattgaaggggccgtttccagttcagatgcttccactgaaaaactg
aaaagcctcggcattcacgtttttgatctcaacgaagtcgacagccttggcatctacgtt
gatggcgcagatgaaatcaacggccacatgcaaatgatcaaaggcggcggcgcggcgctg
acccgtgaaaaaatcattgcttcggttgcagaaaaatttatctgtattgcagacgcttcc
aagcaggttgatattctgggtaaattcccgctgccagtagaagttatcccgatggcacgt
agtgcagtggcgcgtcagctggtgaaactgggcggtcgtccggaataccgtcagggcgtg
gtgaccgataatggcaacgtgatcctcgacgtccacggcatggaaatccttgacccgata
gcgatggaaaacgccataaatgcgattcctggcgtggtgactgttggcttgtttgctaac
cgtggcgcggacgttgcgctgattggcacacctgacggtgtcaaaaccattgtgaaatga');""") 

c.execute("""INSERT INTO enzymes (name, function, EC)
            VALUES ('Isomerase', 'ribose 5-phosphate isomerase', '5.3.1.6');""")

c.execute("""INSERT INTO pathways (name, description)
            VALUES ('Pentose Phosphate', 'a process of glucose turnover that produces NADPH as reducing equivalents and pentoses as essential parts of nucleotides');""")

conn.commit()

In [15]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('Rpi', 'ribose 5-phosphate isomerase A', 'Drosophila', 'atggatgacattgcgctggacgcggccaagaagacggcggcccgcacggcggtggaccag
tgggtgactgaggatacgaagattctggggattggcagcggatcgacggtggtgtacgcc
gtgcagcggatcgcggagcgcgtgtggaaggagggcgagctgacggacctcatctgcgtg
ccctcgtcctaccaggcgcgccatctgatactcgactacaaccttaacctgggcgatctg
gacaggaatcccaacatagacgtggccatcgacggggccgacgaggtcgatcgccatatg
gtgctgatcaagggcggcggcggctgcttgctgcaggagaaggtggtggcctcctgcgcc
aagcacttcatcgtggtggccgactacacaaagaactccatccgcctgggcgagcagtgg
tgccgcggcgtgcccatcgaggtggcgcccatggcgtacgtgcccatcaagctgcacatc
gaggcgcttttcggcggcgaggcctcgttgcgtatggccaaggtgaaggcgggacccatt
gtcacggacaatggcaacttcctcctggactggaagttcatcgccaacagggagtacgac
tgggacgaggtcaaccgcgccatcaccctcatcccgggcgtcctggagacgggcctgttc
gtgaacatggcccacaaatgctactacggcatggccaatggctcggtcaaggtccagaac
aagtag');""") 

conn.commit()

In [16]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('RPIA', 'ribose 5-phosphate isomerase A', 'Homo Sapien', 'atgcagcgccccgggcccttcagcaccctctacgggcgggtcttggccccgctgcccggg
agggccgggggcgcggcctccggcggaggagggaacagctgggacctcccgggttcccac
gtgcggctgccggggcgtgcacagtctgggacccgtggcggtgctggcaacacaagcacc
agctgcggggactccaacagcatctgcccggccccctccacgatgtccaaggccgaggag
gccaagaagctggcgggccgcgcggctgtggagaaccacgtgaggaataaccaagtgctg
ggaattggaagtggttctacaattgtccatgctgtgcagcgaatagctgaaagggtgaag
caagagaatctgaacctcgtctgtattcccacttccttccaggcccgccagctcatcctg
cagtatggcttgaccctcagtgatctggatcgacacccagagatcgaccttgccatcgat
ggtgctgatgaagtagatgctgatctcaatctcatcaagggtggcggaggctgcctgacc
caggagaagattgtggctggctatgctagtcgcttcatcgtgatcgctgatttcaggaaa
gattcgaagaatctcggggatcagtggcacaagggaatccccatcgaggtcatcccaatg
gcctatgtcccagtgagccgagctgtgagccagaagtttgggggcgtggttgaacttcga
atggctgtcaacaaggctggtcctgtggtgacagataatgggaattttatcttggactgg
aagtttgaccgggtacacaaatggagtgaagtgaatacagctatcaaaatgatcccaggt
gtggtggacacaggcctattcatcaacatggctgagagagtctactttgggatgcaggat
ggctcagtgaacatgagggagaagcctttctgttga');""") 

conn.commit()

In [17]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('rbsK', 'ribokinase', 'E. Coli', 'atgcaaaacgcaggcagcctcgttgttcttggcagcattaatgctgaccacattcttaat
cttcaatcttttcctactccaggcgaaaccgtaaccggtaaccactatcaggttgcattt
ggcggcaaaggcgcgaatcaggctgtggctgctgggcgtagcggtgcgaatatcgcgttt
attgcctgtacgggtgatgacagcattggtgagagcgttcgccagcagctcgccactgat
aacattgatattactccggtcagcgtgatcaaaggcgaatcaacaggtgtggcgctgatt
tttgttaatggcgaaggtgagaatgtcatcggtattcatgccggcgctaatgctgccctt
tccccggcgctggtggaagcgcaacgtgagcgtattgccaacgcgtcagcattattaatg
cagctggaatcaccactcgaaagtgtgatggcagcggcgaaaatcgcccatcaaaataag
actatcgttgcgcttaacccggctccggctcgcgaacttcctgacgaactgctggcgctg
gtggacattattacgccaaacgaaacggaagcagaaaagctcaccggtattcgtgttgaa
aatgatgaagatgcagcgaaggcggcgcaggtactgcatgaaaaaggtatccgtactgta
ctgattactttaggaagtcgtggtgtatgggctagcgtgaatggtgaaggtcagcgcgtt
cctggattccgggtgcaggctgtcgataccattgctgccggagatacctttaacggtgcg
ttaatcacggcattgctggaagaaaaaccattgccagaggcgattcgttttgcccatgct
gccgctgcgattgccgtaacacgtaaaggcgcacaaccttccgtaccgtggcgtgaagag
atcgacgcatttttagacaggcagaggtga');""") 

c.execute("""INSERT INTO enzymes (name, function, EC)
            VALUES ('Transferase', 'ribokinase', '2.7.1.15');""")


conn.commit()

In [18]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('RBKS', 'ribokinase', 'Homo sapien', 'atggcggcgtctggggaaccccagaggcagtggcaagaggaggtggcggcggtggtagtg
gtgggctcctgcatgaccgacctggtcagtcttacttctcgtttgccaaaaactggagaa
accatccatggacataagttttttattggctttggagggaaaggtgccaaccagtgtgtc
caagctgctcggcttggagcaatgacgtccatggtgtgtaaggttggcaaagattctttt
ggcaatgattatatagaaaacttaaaacagaatgatatttctacagaatttacatatcag
actaaagatgctgctacaggaactgcttctataattgtcaataatgaaggccagaatatc
attgtcatagtggctggagcaaatttacttttgaatacggaggatctgagggcagcagcc
aatgtcattagcagagccaaagtcatggtctgccagctcgaaataactccagcaacttct
ttggaagccctaacaatggcccgcaggagtggagtgaaaaccttgttcaatccagcccct
gccattgctgacctggatccccagttctacaccctctcagatgtgttctgctgcaatgaa
agtgaggctgagattttaactggcctcacggtgggcagcgctgcagatgctggggaggct
gcattagtgctcttgaaaaggggctgccaggtggtaatcattaccttaggggctgaagga
tgtgtggtgctgtcacagacagaacctgagccaaagcacattcccacagagaaagtcaag
gctgtggataccacgggtgctggtgacagctttgtgggagctctggccttctacctggct
tactatccaaatctgtccttggaagacatgctcaacagatccaatttcattgcagcagtc
agtgtccaggctgcaggaacacagtcatcttacccttacaaaaaagaccttccgcttact
ctgttttga');""") 

conn.commit()

In [19]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('CG13369', 'ribokinase', 'Drosophila', 'atggcccaaacggaagtgctggtgttcggctcggccatcattgactttataagctacacg
acccgtctaccgaaagccggagaaacgctccatgggcatcgctttcagattggctacggc
ggcaagggcgccaatcagtgtgtggctgccgcgcgccagggatcccgaacagctctggtg
gccaaactgggggcagacacattcggcagcgactacctgagacatctgcgcgaggagcgc
gtcaatgtaaaccacgtcgagcagctggcggaggaaacgacgggcgtggcccagatagcc
gtgtcagatggcggcgagaacaacatcatcattgtggtgggcgccaacaatcgactgagc
tcgtgtgacgtttcctcggcgaaggcgctcttccaggaagccaaagttctggtgtgccag
ctggagacgcccgttgaggccaccctgaccgctctgagagccttccggggcgtgtccatc
gtcaatgcggctccggccatggccgacacaccccccgaacttcttcagttggccagcatc
ttctgtgtgaacgaaagcgaggcggcactgatgactcagatgcccgacattggcaacata
gagcacgccgaagatgcggttggaaagctgatagcggcaggtgccaacacggtgatcata
actctgggcaaactaggagccgttttcggttccgccgactccaagggcgtgtgccagcat
gtggctgcgccgagtgtgccgcccgaaaaagtggtggacacgacgggggctggagacgcc
ttcattggggccttggcccacaacttggcccgtcatccaacgaggaaactggaggagcac
atagccgccgcctgtgccgtggcctcgcaatccgttcagctacccgggacgcagtcgagc
ttcccacacgcttag');""") 

conn.commit()

In [20]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('yggf', 'fructose-1,6-bisphosphatase II', 'E. Coli', 'atgatgtccctggcgtggccattatttcgcgttacggaacaggcagcgttggctgcctgg
ccgcaaaccggatgtggcgacaaaaataaaattgatggcctggcggtcaccgcgatgcgc
caggcattaaacgacgtcgcttttcgtggacgagtggttatcggcgaaggagaaattgac
catgcgccgatgctgtggattggcgaagaggtgggcaaaggcgatgggccagaagtcgat
atcgcggttgatcccattgaaggcacgcggatggtggcgatggggcagagcaatgcgctg
gcggtcatggctttcgcccctcgagatagcctgttacatgcgcccgatatgtatatgaaa
aagctggttgttaatcggctggcggcgggcgcgattgatctgtctttgcctctgacggac
aacctgcgcaacgtggcgaaagcgttaggcaaaccgctggataagctgcgcatggttacg
ctggataaaccgcgcctgagtgccgcgattgaggaagcaacacagctgggcgtgaaggtt
tttgccctgccggatggcgatgtcgccgccagcgtgctgacctgctggcaggataatcct
tacgatgtgatgtacaccatcggcggtgcgccagaaggcgtgatttctgcctgtgccgtt
aaagcattaggcggggatatgcaggccgagctgattgacttttgccaggctaaaggggat
tacacggaaaatcggcagattgcagagcaggagcgcaagcgttgcaaggcaatgggcgtt
gacgttaaccgtgtgtactcgctcgatgaactggtgagggggaacgatatcctctttagc
gctacgggcgtgacgggcggtgagctggtgaacggtatccaacagacggcgaatggggtg
cggacgcagacattactgatcggcggcgcggaccaaacgtgtaatataatagactccctg
cattga');""") 

c.execute("""INSERT INTO enzymes (name, function, EC)
            VALUES ('Hydrolase', 'fructose-1,6-bisphosphatase II', '3.1.3.11');""")

conn.commit()

In [21]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('FBP1', 'fructose-1,6-bisphosphatase I', 'Homo sapien', 'atggctgaccaggcgcccttcgacacggacgtcaacaccctgacccgcttcgtcatggag
gagggcaggaaggcccgcggcacgggcgagttgacccagctgctcaactcgctctgcaca
gcagtcaaagccatctcttcggcggtgcgcaaggcgggcatcgcgcacctctatggcatt
gctggttctaccaacgtgacaggtgatcaagttaagaagctggacgtcctctccaacgac
ctggttatgaacatgttaaagtcatcctttgccacgtgtgttctcgtgtcagaagaagat
aaacacgccatcatagtggaaccggagaaaaggggtaaatatgtggtctgttttgatccc
cttgatggatcttccaacatcgattgccttgtgtccgttggaaccatttttggcatctat
agaaagaaatcaactgatgagccttctgagaaggatgctctgcaaccaggccggaacctg
gtggcagccggctacgcactgtatggcagtgccaccatgctggtccttgccatggactgt
ggggtcaactgcttcatgctggacccggccatcggggagttcattttggtggacaaggat
gtgaagataaaaaagaaaggtaaaatctacagccttaacgagggctacgccagggacttt
gaccctgccgtcactgagtacatccagaggaagaagttccccccagataattcagctcct
tatggggcccggtatgtgggctccatggtggctgatgttcatcgcactctggtctacgga
gggatatttctgtaccccgctaacaagaagagccccaatggaaagctgagactgctgtac
gaatgcaaccccatggcctacgtcatggagaaggctgggggaatggccaccactgggaag
gaggccgtgttagacgtcattcccacagacattcaccagagggcgccggtgatcttggga
tcccccgacgacgtgctcgagttcctgaaggtgtatgagaagcactctgcccagtga');""") 

conn.commit()

In [22]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('fbp', 'fructose-1,6-bisphosphatase I', 'Drosophila', 'atgacgctgacgcgtttcgtgctgcaggagcagcgaaagttcaagagcgccactggcgat
ctctcccagctgctcaactccatccagaccgccatcaaggctacatcatccgcggtgcgg
aaggcaggtatcgccaagctccatggattcgctggcgacgtgaatgtccaaggcgaggag
gtcaagaaactggacgtgctctccaacgagctgttcatcaacatgctgaagtcatcctat
accacatgtctaatggtttccgaggagaacgagaatgtgatcgaggtggaagtggagaaa
cagggcaaatacatcgtgtgcttcgatcccttggatggatcctccaacatagactgcctg
gtgtcgatcggttcaatcttcgccatttaccgcaagaaaagcgatggtccgcccacagtg
gaggatgcactgcagcccggaaatcagctggtggccgccggctacgcgctatacggttcg
gccacagcaattgtcctgggtctgggttcgggagtgaatggcttcacttatgacccggcc
atcggagagttcgtgctgaccgatcccaacatgcgggtgccggagaagggaaagatatac
tctatcaacgagggatatgcagcggattgggaggatggtgtcttcaactacattgcggcc
aagaaggatcccgccaagggaaagccctatggagcgcggtacgtgggttccatggtcgcg
gatgtgcatcgcaccattaaatacggcggcatctttatctatccggcaacaaagtccgct
cccagcggaaaacttcgtctgctgtacgagtgcgtgcccatggcctatctgatgatccag
gctggaggtctggccagcgacggaaagatcagcattttggacattgtgcccaagaagatc
cacgagcgcagtcccatattcctaggatccaagtccgacgtggaggaggcacttagctac
ttaaagtga');""") 

conn.commit()

In [23]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('deoC', 'deoxyribose-phosphate aldolase', 'E. Coli', 'atgactgatctgaaagcaagcagcctgcgtgcactgaaattgatggacctgaccaccctg
aatgacgacgacaccgacgagaaagtgatcgccctgtgtcatcaggccaaaactccggtc
ggcaataccgccgctatctgtatctatcctcgctttatcccgattgctcgcaaaactctg
aaagagcagggcaccccggaaatccgtatcgctacggtaaccaacttcccacacggtaac
gacgacatcgacatcgcgctggcagaaacccgtgcggcaatcgcctacggtgctgatgaa
gttgacgttgtgttcccgtaccgcgcgctgatggcgggtaacgagcaggttggttttgac
ctggtgaaagcctgtaaagaggcttgcgcggcagcgaatgtactgctgaaagtgatcatc
gaaaccggcgaactgaaagacgaagcgctgatccgtaaagcgtctgaaatctccatcaaa
gcgggtgcggacttcatcaaaacctctaccggtaaagtggctgtgaacgcgacgccggaa
agcgcgcgcatcatgatggaagtgatccgtgatatgggcgtagaaaaaaccgttggtttc
aaaccggcgggcggcgtgcgtactgcggaagatgcgcagaaatatctcgccattgcagat
gaactgttcggtgctgactgggcagatgcgcgtcactaccgctttggcgcttccagcctg
ctggcaagcctgctgaaagcgctgggtcacggcgacggtaagagcgccagcagctactaa');""") 

c.execute("""INSERT INTO enzymes (name, function, EC)
            VALUES ('Lyase', 'deoxyribose-phosphate aldolase', '4.1.2.4');""")


conn.commit()

In [24]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('DERA', 'deoxyribose-phosphate aldolase', 'Homo Sapien', 'atgtccgcgcacaatcggggcaccgagctcgaccttagctggatctccaaaatacaagtg
aatcacccggcagttctgaggcgtgcggaacaaatccaggctcgcagaaccgtgaaaaag
gagtggcaggctgcttggctcctgaaagctgttacctttatagatcttactacactttca
ggtgatgatacatcttccaacattcaaaggctctgttataaagccaaatacccaatccgg
gaagatctcttaaaagctttaaatatgcatgataaaggcattactacagccgccgtttgt
gtttatcccgcccgggtgtgtgatgctgtaaaagcactcaaggctgcaggctgtaatatc
cctgtggcatcagtggccgctggatttccagctggacagactcatttgaagacacgatta
gaagagatcagattggctgtggaagatggagctacagaaatcgacgtggtaattaacaga
agcttggtgctgacaggccagtgggaagccctgtatgatgagattcgtcagtttcgcaag
gcctgtggggaggctcatcttaaaactatattagcgacaggagaacttggaactcttact
aatgtctataaagccagtatgatagcaatgatggcaggatcagattttattaagacctct
actggaaaagaaacagtaaatgccaccttcccggtagctatagtaatgctgcgggccatt
agagatttcttctggaaaactggaaacaagatagggtttaaaccagcaggaggcatccgc
agtgcaaaggattcccttgcttggctctctcttgtaaaggaggagcttggagatgagtgg
ctgaagccagaactctttcgaataggtgccagtactctgctctcggacattgagaggcag
atttaccatcatgtgactggaagatatgcagcttatcatgatcttccaatgtcttaa');""") 

conn.commit()

In [25]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('Dera', 'deoxyribose-phosphate aldolase', 'Drosophila', 'atgagcagcatggatgtgaaggaattggaagtaaacaaaaccctgccctatgatccctcc
ctgcttaaggtaaacatctcgctgcggcaggtcgaggagatcgctttgacggtgtcccag
cgatgccatgtcaccggagccaacgaaatcgcctgggcgctgagggctctgatgctgaca
gatcttaccaccttggcgggcgatgatacggctgccaatgtgcggagactatgcctacgc
gcctgctatcccttcgagccgcagttctttgacaagttcttcgaccgggctctcatccca
gagatgcacacggccgccgtttgcgtttatcccgccagggtaaaggacgcctatttagct
atccaacagtacgacaaactggataaggtggctattgcagcggtggccacgggatttccc
acgggccagtacggcctgcagacccgcctgcaggagatcagccacgccattcttgctgga
gccacagagatcgacattgtgatcaatcgccagttggccctcgttggcgactgggaggcc
atgtacaacgaggtggtccttatgcgcagtgcctgtggacaaagggctcacctaaaaaca
attctggccatcggggagctgggcaccatggataatgtttacaaagcagccatggtttgc
atgatggccggagcggattttatcaagacctcaacgggaaaggagacagtcaacgccacc
ctgcccgttggcctggtcatgatatttgccattcaggaattcaaacgacgcacgtgccag
attgtgggccttaagccagccggaggagtaaagactgtacgagatgcgatcgcctggatg
acgttggtcaacgaaactcttggcatccgctggttgcgtcccgagaggttccgtttcgga
gcctccggattgctggacgacattgaacgcgttgtgcgtcagggtgtcaaaaaactcgag
gaggatgaggctcagaaaaatgtgcccgtgtctcgcgaggctgctgctgccgagaccttc
tgcaaggagctgcggaagaagtag');""") 

conn.commit()

In [26]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('sucB', 'dihydrolipoyltranssuccinylase', 'E. Coli', 'atgagtagcgtagatattctggtccctgacctgcctgaatccgtagccgatgccaccgtc
gcaacctggcataaaaaacccggcgacgcagtcgtacgtgatgaagtgctggtagaaatc
gaaactgacaaagtggtactggaagtaccggcatcagcagacggcattctggatgcggtt
ctggaagatgaaggtacaacggtaacgtctcgtcagatccttggtcgcctgcgtgaaggc
aacagcgccggtaaagaaaccagcgccaaatctgaagagaaagcgtccactccggcgcaa
cgccagcaggcgtctctggaagagcaaaacaacgatgcgttaagcccggcgatccgtcgc
ctgctggctgaacacaatctcgacgccagcgccattaaaggcaccggtgtgggtggtcgt
ctgactcgtgaagatgtggaaaaacatctggcgaaagccccggcgaaagagtctgctccg
gcagcggctgctccggcggcgcaaccggctctggctgcacgtagtgaaaaacgtgtcccg
atgactcgcctgcgtaagcgtgtggcagagcgtctgctggaagcgaaaaactccaccgcc
atgctgaccacgttcaacgaagtcaacatgaagccgattatggatctgcgtaagcagtac
ggtgaagcgtttgaaaaacgccacggcatccgtctgggctttatgtccttctacgtgaaa
gcggtggttgaagccctgaaacgttacccggaagtgaacgcttctatcgacggcgatgac
gtggtttaccacaactatttcgacgtcagcatggcggtttctacgccgcgcggcctggtg
acgccggttctgcgtgatgtcgataccctcggcatggcagacatcgagaagaaaatcaaa
gagctggcagtcaaaggccgtgacggcaagctgaccgttgaagatctgaccggtggtaac
ttcaccatcaccaacggtggtgtgttcggttccctgatgtctacgccgatcatcaacccg
ccgcagagcgcaattctgggtatgcacgctatcaaagatcgtccgatggcggtgaatggt
caggttgagatcctgccgatgatgtacctggcgctgtcctacgatcaccgtctgatcgat
ggtcgcgaatccgtgggcttcctggtaacgatcaaagagttgctggaagatccgacgcgt
ctgctgctggacgtgtag');""") 

c.execute("""INSERT INTO enzymes (name, function, EC)
            VALUES ('Transferase', 'dihydrolipoyllysine-residue succinyltransferase', '2.3.1.61');""")

c.execute("""INSERT INTO pathways (name, description)
            VALUES ('TCA Cycle', 'an important aerobic pathway for the final steps of the oxidation of carbohydrates and fatty acids');""")

conn.commit()

In [27]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('DLST', 'dihydrolipoyltranssuccinylase', 'Homo sapien', 'atgctgtcccgatcccgctgtgtgtctcgggcgttcagccgctcgctctccgccttccag
aaggggaactgccctctagggagacgttccctgcctggggtctccttatgccagggacca
ggttaccctaacagcaggaaggttgtcattaacaacagtgtcttcagtgttcgctttttc
agaactacagctgtatgcaaggatgacttggttacagtcaaaaccccagcgtttgcagaa
tctgtcacagagggagatgtcaggtgggagaaagctgttggagacacagttgcagaagat
gaagtggtttgtgagattgaaactgacaagacatctgtgcaggttccatcaccagcaaat
ggcgtgattgaagctcttttggtacctgatgggggaaaagtcgaaggaggcactccactt
ttcacactcaggaaaactggtgctgctcctgctaaggccaagccggctgaagctcctgct
gctgcagccccaaaagcagaacctacagcagcggcagttcctccccctgcagcacccata
cccactcagatgccaccggtgccctcgccctcacagcctccttctggcaaacctgtgtct
gcagtaaaacccactgttgccccaccactagctgagccaggagctggcaaaggtctgcgt
tcagaacatcgggagaaaatgaacaggatgcggcagcgcattgctcagcgtctgaaggag
gcccagaatacatgtgcaatgctgacaacttttaatgagattgacatgagtaacatccag
gagatgagggctcggcacaaagaggcttttttgaagaaacataacctcaaactaggcttc
atgtcggcatttgtgaaggcctcagcctttgccttgcaggaacagcctgttgtaaatgca
gtgattgacgacacaaccaaagaggtggtgtatagggattatattgacatcagtgttgca
gtggccaccccacggggtctggtggttccagtcatcaggaatgtggaagctatgaatttt
gcagatattgaacggaccatcactgaactgggagagaaggcccgaaagaatgaacttgcc
attgaagatatggatggcggtaccttcaccattagcaatggaggcgtttttggctcgctc
tttggaacacccattatcaacccccctcagtctgccatcctggggatgcatggcatcttt
gacaggccagtggctataggaggcaaggtagaggtgcggcccatgatgtacgtggcactg
acctatgatcaccggctgattgatggcagagaggctgtgactttcctccgcaaaatcaag
gcagcggtagaggatcccagagtcctcctcctggatctttag');""") 

conn.commit()

In [28]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('CH5214', 'dihydrolipoamide succinyltransferase', 'Drosophila', 'atgacgggaataatttcgatcgtaacgagacggctgccccaaactttgggaatgcgagcc
ctgcggagtaatgaggtaaagcgctgcatccgccaatattctcggttagttgcctgcgcc
gcccagcagcagcaactgcttcgccaggatggctcgaatcgctgccaggaggccaccagg
cttctcacctggcagggaatccacaccacgtcgagcttgtggtcggagcagaccgtcaat
gtgccaccctttgcggactccattgccgagggtgacatcaagtttacttgcaaggtgggt
gactcattcgccgctgacgaggctgtcatggaaatcgagaccgacaagacgacggtggct
gtgccagctcccttctccggaactctaaccgacattctggtgaaggatggcgacaccgtc
aagcccggccaggctctgttcaagatcaagcccggtgcagcgcccgccaaggcagctgct
ccagcggctgctcctgcgcctgctgccccaaaagcagcaccagctccagctgctgcaccc
aagccggcacctccaccacctgcggccggcgcaccaaagccaccaccaccgccaccacca
aaggcagcccctcgaccaccgccacctgctccagtggctgcactcaaaccggccgtcgcc
caggtgaaggtgccaccagcggacggatcgcggcagatcctaggcactaggtccgagcag
cgtgtcaagatgaaccgcatgcgtctaaagattgccgcccgcttgaaggatgcccagaac
acatgtgccatgctcaccactttcaacgaggttgatatgagctatgccatggacttccga
aagcagaatctggatgcgttcactaagaagtatggtattaagtttggattcatgtcgatc
ttcgccaaggctagtgcctatgcgctgcaggatcagcccgtagtgaacgccgtcatcgat
ggcacggacatcgtgtatcgcgactacgttgacatctctgtggccgtggctacgccccgt
ggattggtggtacccgtcatccgcaacgtggagggcatgaactatgcggacatcgagatc
gcactggccggtctggccgataaggccaggcgtgatgccatcaccgtggaggacatggac
ggtggcaccttcaccatcagcaatggcggagtgttcggatccctgatgggcacgcccatc
atcaatccgccacagagtgccattctcggcatgcacggcatctttgagcggccaattgct
gtcaagggagaggtcaagatacgtcctatgatgtacatcgccctgacctacgatcaccga
atcattgatggacgtgaggcggtcctgttcctgcgaaaaataaaggctgccgtagagaac
ccagcaataattgttgccggattgtaa');""") 

conn.commit()

In [29]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('mdh', 'malate dehydrogenase', 'E. Coli', 'atgaaagtcgcagtcctcggcgctgctggcggtattggccaggcgcttgcactactgtta
aaaacccaactgccttcaggttcagaactctctctgtatgatatcgctccagtgactccc
ggtgtggctgtcgatctgagccatatccctactgctgtgaaaatcaaaggtttttctggt
gaagatgcgactccggcgctggaaggcgcagatgtcgttcttatctctgcaggcgtagcg
cgtaaaccgggtatggatcgttccgacctgtttaacgttaacgccggcatcgtgaaaaac
ctggtacagcaagttgcgaaaacctgcccgaaagcgtgcattggtattatcactaacccg
gttaacaccacagttgcaattgctgctgaagtgctgaaaaaagccggtgtttatgacaaa
aacaaactgttcggcgttaccacgctggatatcattcgttccaacacctttgttgcggaa
ctgaaaggcaaacagccaggcgaagttgaagtgccggttattggcggtcactctggtgtt
accattctgccgctgctgtcacaggttcctggcgttagttttaccgagcaggaagtggct
gatctgaccaaacgcatccagaacgcgggtactgaagtggttgaagcgaaggccggtggc
gggtctgcaaccctgtctatgggccaggcagctgcacgttttggtctgtctctggttcgt
gcactgcagggcgaacaaggcgttgtcgaatgtgcctacgttgaaggcgacggtcagtac
gcccgtttcttctctcaaccgctgctgctgggtaaaaacggcgtggaagagcgtaaatct
atcggtaccctgagcgcatttgaacagaacgcgctggaaggtatgctggatacgctgaag
aaagatatcgccctgggcgaagagttcgttaataagtaa');""") 

c.execute("""INSERT INTO enzymes (name, function, EC)
            VALUES ('Transferase', 'malate dehydrogenase', '1.1.1.37');""")

conn.commit()

In [30]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('MDH1', 'malate dehydrogenase', 'Homo sapien', 'atgtctgaaccaatcagagtccttgtgactggagcagctggtcaaattgcatattcactg
ctgtacagtattggaaatggatctgtctttggtaaagatcagcctataattcttgtgctg
ttggatatcacccccatgatgggtgtcctggacggtgtcctaatggaactgcaagactgt
gcccttcccctcctgaaagatgtcatcgcaacagataaagaagacgttgccttcaaagac
ctggatgtggccattcttgtgggctccatgccaagaagggaaggcatggagagaaaagat
ttactgaaagcaaatgtgaaaatcttcaaatcccagggtgcagccttagataaatacgcc
aagaagtcagttaaggttattgttgtgggtaatccagccaataccaactgcctgactgct
tccaagtcagctccatccatccccaaggagaacttcagttgcttgactcgtttggatcac
aaccgagctaaagctcaaattgctcttaaacttggtgtgactgctaatgatgtaaagaat
gtcattatctggggaaaccattcctcgactcagtatccagatgtcaaccatgccaaggtg
aaattgcaaggaaaggaagttggtgtttatgaagctctgaaagatgacagctggctcaag
ggagaatttgtcacgactgtgcagcagcgtggcgctgctgtcatcaaggctcgaaaacta
tccagtgccatgtctgctgcaaaagccatctgtgaccacgtcagggacatctggtttgga
accccagagggagagtttgtgtccatgggtgttatctctgatggcaactcctatggtgtt
cctgatgatctgctctactcattccctgttgtaatcaagaataagacctggaagtttgtt
gaaggtctccctattaatgatttctcacgtgagaagatggatcttactgcaaaggaactg
acagaagaaaaagaaagtgcttttgaatttctttcctctgcctga');""") 

conn.commit()

In [31]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('CG10748', 'malate dehydrogenase', 'Drosophila', 'atgacgggaataatttcgatcgtaacgagacggctgccccaaactttgggaatgcgagcc
ctgcggagtaatgaggtaaagcgctgcatccgccaatattctcggttagttgcctgcgcc
gcccagcagcagcaactgcttcgccaggatggctcgaatcgctgccaggaggccaccagg
cttctcacctggcagggaatccacaccacgtcgagcttgtggtcggagcagaccgtcaat
gtgccaccctttgcggactccattgccgagggtgacatcaagtttacttgcaaggtgggt
gactcattcgccgctgacgaggctgtcatggaaatcgagaccgacaagacgacggtggct
gtgccagctcccttctccggaactctaaccgacattctggtgaaggatggcgacaccgtc
aagcccggccaggctctgttcaagatcaagcccggtgcagcgcccgccaaggcagctgct
ccagcggctgctcctgcgcctgctgccccaaaagcagcaccagctccagctgctgcaccc
aagccggcacctccaccacctgcggccggcgcaccaaagccaccaccaccgccaccacca
aaggcagcccctcgaccaccgccacctgctccagtggctgcactcaaaccggccgtcgcc
caggtgaaggtgccaccagcggacggatcgcggcagatcctaggcactaggtccgagcag
cgtgtcaagatgaaccgcatgcgtctaaagattgccgcccgcttgaaggatgcccagaac
acatgtgccatgctcaccactttcaacgaggttgatatgagctatgccatggacttccga
aagcagaatctggatgcgttcactaagaagtatggtattaagtttggattcatgtcgatc
ttcgccaaggctagtgcctatgcgctgcaggatcagcccgtagtgaacgccgtcatcgat
ggcacggacatcgtgtatcgcgactacgttgacatctctgtggccgtggctacgccccgt
ggattggtggtacccgtcatccgcaacgtggagggcatgaactatgcggacatcgagatc
gcactggccggtctggccgataaggccaggcgtgatgccatcaccgtggaggacatggac
ggtggcaccttcaccatcagcaatggcggagtgttcggatccctgatgggcacgcccatc
atcaatccgccacagagtgccattctcggcatgcacggcatctttgagcggccaattgct
gtcaagggagaggtcaagatacgtcctatgatgtacatcgccctgacctacgatcaccga
atcattgatggacgtgaggcggtcctgttcctgcgaaaaataaaggctgccgtagagaac
ccagcaataattgttgccggattgtaa');""") 

conn.commit()

In [32]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('lpd', 'dihydrolipoamide dehydrogenase', 'E. Coli', 'atgagtactgaaatcaaaactcaggtcgtggtacttggggcaggccccgcaggttactcc
gctgccttccgttgcgctgatttaggtctggaaaccgtaatcgtagaacgttacaacacc
cttggcggtgtttgcctgaacgtcggctgtatcccttctaaagcactgctgcacgtagca
aaagttatcgaagaagccaaagcgctggctgaacacggtatcgtcttcggcgaaccgaaa
accgatatcgacaagattcgtacctggaaagagaaagtgatcaatcagctgaccggtggt
ctggctggtatggcgaaaggccgcaaagtcaaagtggtcaacggtctgggtaaattcacc
ggggctaacaccctggaagttgaaggtgagaacggcaaaaccgtgatcaacttcgacaac
gcgatcattgcagcgggttctcgcccgatccaactgccgtttattccgcatgaagatccg
cgtatctgggactccactgacgcgctggaactgaaagaagtaccagaacgcctgctggta
atgggtggcggtatcatcggtctggaaatgggcaccgtttaccacgcgctgggttcacag
attgacgtggttgaaatgttcgaccaggttatcccggcagctgacaaagacatcgttaaa
gtcttcaccaagcgtatcagcaagaaattcaacctgatgctggaaaccaaagttaccgcc
gttgaagcgaaagaagacggcatttatgtgacgatggaaggcaaaaaagcacccgctgaa
ccgcagcgttacgacgccgtgctggtagcgattggtcgtgtgccgaacggtaaaaacctc
gacgcaggcaaagcaggcgtggaagttgacgaccgtggtttcatccgcgttgacaaacag
ctgcgtaccaacgtaccgcacatctttgctatcggcgatatcgtcggtcaaccgatgctg
gcacacaaaggtgttcacgaaggtcacgttgccgctgaagttatcgccggtaagaaacac
tacttcgatccgaaagttatcccgtccatcgcctataccgaaccagaagttgcatgggtg
ggtctgactgagaaagaagcgaaagagaaaggcatcagctatgaaaccgccaccttcccg
tgggctgcttctggtcgtgctatcgcttccgactgcgcagacggtatgaccaagctgatt
ttcgacaaagaatctcaccgtgtgatcggtggtgcgattgtcggtactaacggcggcgag
ctgctgggtgaaatcggcctggcaatcgaaatgggttgtgatgctgaagacatcgcactg
accatccacgcgcacccgactctgcacgagtctgtgggcctggcggcagaagtgttcgaa
ggtagcattaccgacctgccgaacccgaaagcgaagaagaagtaa');""") 

c.execute("""INSERT INTO enzymes (name, function, EC)
            VALUES ('Oxidoreductases', 'dihydrolipoamide dehydrogenase', '1.8.1.4');""")

conn.commit()

In [33]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('DLD', 'dihydrolipoamide dehydrogenase', 'Homo sapien', 'atgcagagctggagtcgtgtgtactgctccttggccaagagaggccatttcaatcgaata
tctcatggcctacagggactttctgcagtgcctctgagaacttacgcagatcagccgatt
gatgctgatgtaacagttataggttctggtcctggaggatatgttgctgctattaaagct
gcccagttaggcttcaagacagtctgcattgagaaaaatgaaacacttggtggaacatgc
ttgaatgttggttgtattccttctaaggctttattgaacaactctcattattaccatatg
gcccatggaaaagattttgcatctagaggaattgaaatgtccgaagttcgcttgaattta
gacaagatgatggagcagaagagtactgcagtaaaagctttaacaggtggaattgcccac
ttattcaaacagaataaggttgttcatgtcaatggatatggaaagataactggcaaaaat
caagtcactgctacgaaagctgatggcggcactcaggttattgatacaaagaacattctt
atagccacgggttcagaagttactccttttcctggaatcacgatagatgaagatacaata
gtgtcatctacaggtgctttatctttaaaaaaagttccagaaaagatggttgttattggt
gcaggagtaataggtgtagaattgggttcagtttggcaaagacttggtgcagatgtgaca
gcagttgaatttttaggtcatgtaggtggagttggaattgatatggagatatctaaaaac
tttcaacgcatccttcaaaaacaggggtttaaatttaaattgaatacaaaggttactggt
gctaccaagaagtcagatggaaaaattgatgtttctattgaagctgcttctggtggtaaa
gctgaagttatcacttgtgatgtactcttggtttgcattggccgacgaccctttactaag
aatttgggactagaagagctgggaattgaactagatcccagaggtagaattccagtcaat
accagatttcaaactaaaattccaaatatctatgccattggtgatgtagttgctggtcca
atgctggctcacaaagcagaggatgaaggcattatctgtgttgaaggaatggctggtggt
gctgtgcacattgactacaattgtgtgccatcagtgatttacacacaccctgaagttgct
tgggttggcaaatcagaagagcagttgaaagaagagggtattgagtacaaagttgggaaa
ttcccatttgctgctaacagcagagctaagacaaatgctgacacagatggcatggtgaag
atccttgggcagaaatcgacagacagagtactgggagcacatattcttggaccaggtgct
ggagaaatggtaaatgaagctgctcttgctttggaatatggagcatcctgtgaagatata
gctagagtctgtcatgcacatccgaccttatcagaagcttttagagaagcaaatcttgct
gcgtcatttggcaaatcaatcaacttttga');""") 

conn.commit()

In [34]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('CH7430', 'dihydrolipoamide dehydrogenase', 'Drosophila', 'atgcaattcacgctccgtcatgttgtttcggcagtagccaagactcctctgcgcaccaat
gccgccattctgggtgccctcaacgcccgctgctactccagcacccacgaggcggacatc
gtggtgattggctccggacccggtggctatgtcgccgccatcaaggccgcccagatgggc
atgaagacggtcagcgtggagaaggaggcaactctgggcggcacctgcctgaatgttggc
tgcattccctcaaaggcgctgctgaacaactcccactactaccacatggcccactccggt
gatctggagaaacgtggtattagctgcggcagcgttagcctggatctggagaagcttatg
ggtcaaaagtccaacgccgtgaaggctttgaccggtggcattgccatgcttttcaagaag
aacaaggtcacacagctgacgggcttcggcaccatcgtcaatcccaacgaggtggaggtt
aagaaatccgacggctccacggagactgtcaagaccaagaacatcctcatcgccaccggc
tcggaggttacccccttccctggcattgaaatcgacgaggaagttattgtgagcagcact
ggcgccctgaagctggccaaggtgcccaagcatctggttgtcatcggcgccggtgtcatt
ggcctggagctgggttcggtatggtcgcgtctgggcgctgaggtcactgccattgagttc
atggatacgatcggcggcgtgggcatcgataacgaagtctccaagacgttccaaaaggtg
ctcaccaagcagggtcttaagttcaagctgggcaccaaggtgacggctgcctctcgcagc
ggcgacaacgtcaccgtgtccgtggagaacgccaagtctggcgagaaagaggagatccag
tgcgacgccctgctggtcagtgttggacgtcgtccctacaccgaaggtttgggtctggag
gccgtgggcattgttaaggatgaccgcggcaggatccccgtcaacgccactttccaaact
gtggtgcccaatatttacgccatcggcgactgcatccacggacccatgttggcgcacaag
gctgaagatgagggcctcatcaccattgagggcatcaacggcggccacgtgcacatcgac
tacaactgcgtgcccagtgtagtctacacgcatcccgaggtcgcgtgggttggcaagagc
gaggagcaactgaagcaggagggtgttgcctacaaggtgggcaagttccccttcctggcc
aactctcgtgccaagaccaacaacgacaccgacggtttcgtcaaggttctggccgaccag
gccaccgataagatcctgggaacccatattatcggacctggtgccggcgagctcattaac
gaggctgtgctggccatggagtacggagccgctgccgaggacgttgcccgcgtttgccat
gcgcatccaacatgttccgaggccctgcgtgaggccaatgtggcagctgcctttggcaaa
cccatcaacttctaa');""") 

conn.commit()

In [35]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('acnB', '2-methylisocitrate dehydratase', 'E. Coli', 'gtgctagaagaataccgtaagcacgtagctgagcgtgccgctgaggggattgcgcccaaa
cccctggatgcaaaccaaatggccgcacttgtagagctgctgaaaaacccgcccgcgggc
gaagaagaattcctgttagatctgttaaccaaccgtgttcccccaggcgtcgatgaagcc
gcctatgtcaaagcaggcttcctggctgctatcgcgaaaggcgaagccaaatcccctctg
ctgactccggaaaaagccatcgaactgctgggcaccatgcagggtggttacaacattcat
ccgctgatcgacgcgctggatgatgccaaactggcacctattgctgccaaagcactttct
cacacgctgctgatgttcgataacttctatgacgtagaagagaaagcgaaagcaggcaac
gaatatgcgaagcaggttatgcagtcctgggcggatgccgaatggttcctgaatcgcccg
gcgctggctgaaaaactgaccgttactgtcttcaaagtcactggcgaaactaacaccgat
gacctttctccggcaccggatgcgtggtcacgcccggatatcccactgcacgcgctggcg
atgctgaaaaacgcccgtgaaggtattgagccagaccagcctggtgttgttggtccgatc
aagcaaatcgaagctctgcaacagaaaggtttcccgctggcgtacgtcggtgacgttgtg
ggtacgggttcttcgcgtaaatccgccactaactccgttctgtggtttatgggcgatgat
attccacatgtgccgaacaaacgcggcggtggtttgtgcctcggcggtaaaattgcaccc
atcttctttaacacgatggaagacgcgggtgcactgccaatcgaagtcgacgtctctaac
ctgaacatgggcgacgtgattgacgtttacccgtacaaaggtgaagtgcgtaaccacgaa
accggcgaactgctggcgaccttcgaactgaaaaccgacgtgctgattgatgaagtgcgt
gctggtggccgtattccgctgattatcgggcgtggcctgaccaccaaagcgcgtgaagca
cttggtctgccgcacagtgatgtgttccgtcaggcgaaagatgtcgctgagagcgatcgc
ggcttctcgctggcgcaaaaaatggtaggccgtgcctgtggcgtgaaaggcattcgtccg
ggcgcgtactgtgaaccgaaaatgacttctgtaggttcccaggacaccaccggcccgatg
acccgtgatgaactgaaagacctggcgtgcctgggcttctcggctgacctggtgatgcag
tctttctgccacaccgcggcgtatccgaagccagttgacgtgaacacgcaccacacgctg
ccggacttcattatgaaccgtggcggtgtgtcgctgcgtccgggtgacggcgtcattcac
tcctggctgaaccgtatgctgctgccggataccgtcggtaccggtggtgactcccatacc
cgtttcccgatcggtatctctttcccggcgggttctggtctggtggcgtttgctgccgca
actggcgtaatgccgcttgatatgccggaatccgttctggtgcgcttcaaaggcaaaatg
cagccgggcatcaccctgcgcgatctggtacacgctattccgctgtatgcgatcaaacaa
ggtctgctgaccgttgagaagaaaggcaagaaaaacatcttctctggccgcatcctggaa
attgaaggtctgccggatctgaaagttgagcaggcctttgagctaaccgatgcgtccgcc
gagcgttctgccgctggttgtaccatcaagctgaacaaagaaccgatcatcgaatacctg
aactctaacatcgtcctgctgaagtggatgatcgcggaaggttacggcgatcgtcgtacc
ctggaacgtcgtattcagggcatggaaaaatggctggcgaatcctgagctgctggaagcc
gatgcagatgcggaatacgcggcagtgatcgacatcgatctggcggatattaaagagcca
atcctgtgtgctccgaacgacccggatgacgcgcgtccgctgtctgcggtacagggtgag
aagatcgacgaagtgtttatcggttcctgcatgaccaacatcggtcacttccgtgctgcg
ggtaaactgctggatgcgcataaaggtcagttgccgacccgcctgtgggtggcaccgcca
acccgtatggacgccgcacagttgaccgaagaaggctactacagcgtcttcggtaagagt
ggtgcgcgtatcgagatccctggctgttccctgtgtatgggtaaccaggcgcgtgtggcg
gacggtgcaacggtggtttccacctctacccgtaacttcccgaaccgtctgggtactggc
gcgaatgtcttcctggcttctgcggaactggcggctgttgcggcgctgattggcaaactg
ccgacgccggaagagtaccagacctacgtggcgcaggtagataaaacagccgttgatact
taccgttatctgaacttcaaccagctttctcagtacaccgagaaagccgatggggtgatt
ttccagactgcggtttaa');""") 

c.execute("""INSERT INTO enzymes (name, function, EC)
            VALUES ('Lyase', '2-methylisocitrate dehydratase', '4.2.1.3');""")

conn.commit()

In [36]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('ACO1', 'aconitate hydratase', 'Homo sapien', 'atgagcaacccattcgcacaccttgctgagccattggatcctgtacaaccaggaaagaaa
ttcttcaatttgaataaattggaggattcaagatatgggcgcttaccattttcgatcaga
gttcttctggaagcagccattcggaattgtgatgagtttttggtgaagaaacaggatatt
gaaaatattctacattggaatgtcacgcagcacaagaacatagaagtgccatttaagcct
gctcgtgtcatcctgcaggactttacgggtgtgcccgctgtggttgactttgctgcaatg
cgtgatgctgtgaaaaagttaggaggagatccagagaaaataaaccctgtctgccctgct
gatcttgtaatagatcattccatccaggttgatttcaacagaagggcagacagtttacag
aagaatcaagacctggaatttgaaagaaatagagagcgatttgaatttttaaagtggggt
tcccaggcttttcacaacatgcggattattccccctggctcaggaatcatccaccaggtg
aatttggaatatttggcaagagtggtatttgatcaggatggatattattacccagacagc
ctcgtgggcacagactcgcacactaccatgattgatggcttgggcattcttggttggggt
gtcggtggtattgaagcagaagctgtcatgctgggtcagccaatcagtatggtgcttcct
caggtgattggctacaggctgatggggaagccccaccctctggtaacatccactgacatc
gtgctcaccattaccaagcacctccgccaggttggggtagtgggcaaatttgtcgagttc
ttcgggcctggagtagcccagttgtccattgctgaccgagctacgattgctaacatgtgt
ccagagtacggagcaactgctgcctttttcccagttgatgaagttagtatcacgtacctg
gtgcaaacaggtcgtgatgaagaaaaattaaagtatattaaaaaatatcttcaggctgta
ggaatgtttcgagatttcaatgacccttctcaagacccagacttcacccaggttgtggaa
ttagatttgaaaacagtagtgccttgctgtagtggacccaaaaggcctcaggacaaagtt
gctgtgtccgacatgaaaaaggactttgagagctgccttggagccaagcaaggatttaaa
ggattccaagttgctcctgaacatcataatgaccataagacctttatctatgataacact
gaattcacccttgctcatggttctgtggtcattgctgccattactagctgcacaaacacc
agtaatccgtctgtgatgttaggggcaggattgttagcaaagaaagctgtggatgctggc
ctgaacgtgatgccttacatcaaaactagcctgtctcctgggagtggcgtggtcacctac
tacctacaagaaagcggagtcatgccttatctgtctcagcttgggtttgacgtggtgggc
tatggctgcatgacctgcattggcaacagtgggcctttacctgaacctgtggtagaagcc
atcacacagggagaccttgtagctgttggagtactatctggaaacaggaattttgaaggt
cgagttcaccccaacacccgggccaactatttagcctctccccccttagtaatagcatat
gcaattgctggaaccatcagaatcgactttgagaaagagccattgggagtaaatgcaaag
ggacagcaggtatttctgaaagatatctggccgactagagacgagatccaggcagtggag
cgtcagtatgtcatcccggggatgtttaaggaagtctatcagaaaatagagactgtgaat
gaaagctggaatgccttagcaaccccatcagataagctgtttttctggaattccaaatct
acgtatatcaaatcaccaccattctttgaaaacctgactttggatcttcagccccctaaa
tctatagtggatgcctatgtgctgctaaatttgggagattcggtaacaactgaccacatc
tccccagctggaaatattgcaagaaacagtcctgctgctcgctacttaactaacagaggc
ctaactccacgagaattcaactcctatggctcccgccgaggtaatgacgccgtcatggca
cggggaacatttgccaacattcgcttgttaaacagatttttgaacaagcaggcaccacag
actatccatctgccttctggggaaatccttgatgtgtttgatgctgctgagcggtaccag
caggcaggccttcccctgatcgttctggctggcaaagagtacggtgcaggcagctcccga
gactgggcagctaagggccctttcctgctgggaatcaaagccgtcctggccgagagctac
gagcgcattcaccgcagtaacctggttgggatgggtgtgatcccacttgaatatctccct
ggtgagaatgcagatgccctggggctcacagggcaagaacgatacactatcattattcca
gaaaacctcaaaccacaaatgaaagtccaggtcaagctggatactggcaagaccttccag
gctgtcatgaggtttgacactgatgtggagctcacttatttcctcaacgggggcatcctc
aactacatgatccgcaagatggccaagtag');""") 

conn.commit()

In [37]:
c.execute("""INSERT INTO genes (name, description, organism, sequence) 
            VALUES ('mAcon2', 'aconitate hydratase', 'Drosophila', 'atggctcaacgaacacatagatatatatgtttggcgggttccatggtgcgaaactttcac
acggcgcgttttccacgatgtgataaagtggcaatgtcaaattttgataccggaattccc
ttgccctataagaagttgagggaaaacctggattgcatcaagggtcgactgggtggaccg
ctaaccttgtcggagaaggtgttatattcccatttggatcaaccggattcacaggaaatc
gaacgaggcaagtcctatttgcgattgcgaccagatcgcgttgccctgcaggatgcgact
gcccagatgacgctactgcagttcatttcgtcgggcctgaagaaggtagcagttccatcc
accgtccactgtgatcacttaattgaggcccagatcagtggcgataaggacttggccagg
gctaaggatctgaacaaggaggtgtacgattttctgtcctcggcgtgtgccaagtataac
ttgggtttctggaagcctggcagcggcataattcatcagatcattttagagaactatgca
tttcccggactactgatgatcggaactgattcccatactccgaatggcggcggattgggt
tgcctatgcgttggagttggtggtgctgatgccgtcgatgtgatggcgaatataccgtgg
gaactcaagtgcccgaccgtgattggatgccatctcacgggtaagatcagtgggtggact
tcgcccaaggatgtcatccttaaagtggccgagattctgaccgttaaaggaggtacgggt
gccattgtggagtaccatggtcctggcgtcgaatctatttcctgcacaggcatggctact
attaccaacatgggtgctgaaatcggtgccacaacttcaatatttccattcaacgaacgc
atggtcacatatttgcgtgcaaccggtagaggtgccatcgctgatgaggccacaaagaat
aaagatcttttggttccggatgagggttgcaaatacgataaggtgatcgagatcaatttg
gacaccttggaaccgctggtgaatggccccttcactcccgatttggcccatcccattagt
aaactgggtcagaactccgagaagaatggctatccgatggaaatcaaagtgagtctaatt
ggttcctgcacgaactcctcctacgaggacatgggacgatgtgccagcatagccaatgac
gcactgggtcatggcctaaaatcgtgcgttccatttaatgttaccccgggatcggagcaa
gttcgagctacaatcgcacgggacggcattatagatgtgcttgagaagtttggaggcacc
gtgctggcgaatgcctgtggtccctgcattggacagtgggatcgcaaggatgtaaagatg
ggagagaagaacaccattgtcacgtcgtataatcgcaacttcaccggtcgaaatgatgcc
aatccagcaacacattgttttgttacgagtccagaaatggcaactgcattggctatcgcc
ggacgtttggatttcaatccgatgacggatgagcttacgggtaccgatggcaaaacgttc
aagctcaaggaaccgcacggcgaagagctgccatccaagggttttgatcccggagaggat
acctatcaggctcccccagcgaaagcagatgatatcaaggtcaatgtcgatcccaagtcg
gatcgcctgcaactgctcgaaccttttgagaaatgggacggcaaggactacattgatttg
atggtgcttatcaaaatcaaaggcaaatgcaccaccgatcacatcagtgccgctggaccc
tggcttaagtatcgcggtcatttggataatatatcaaataacatgttcattggggcaaca
aatgccgaaaacaatgaaatgaacaaggtcaaaaaccagaagacaggcagttttgacgcc
gtaccagcggtggcacgcgattacaaggccaacaagatcaagtggtgtgctgtgggtgag
gagaactacggcgagggatcatccagggagcacgctgccctggaacctcgacacttgggc
ggagtggccattatcgtcaagtcgttcgcccgcatccacgagacgaacctaaagaaacag
ggtatgctcgccctgacattcgccaatcccggtgactacgacaaagttcagccgtcgagc
aagatttcgatactgaacctcaaggacttggcacctggcaagcctgtggatgctgagatc
aagaataatggtagctccgacaaaatccagttgaaccacacccttaatgagctgcagatc
cagtggttccaggctggaagtgccttgaatctaatgaaggagcttgccgccaagggtggc
gataagaaatag');""") 

conn.commit()